name: SIPKES CI/CD Pipeline

on:
  push:
    branches:
      - main
      - rahma-cloud-docs
  pull_request:
    branches:
      - main

jobs:
  build-test-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Test
        working-directory: ./backend
        run: npm test --if-present

      - name: Build Backend Docker Image
        run: docker build -t sipkes-backend:latest ./backend

      - name: Build Frontend Docker Image
        run: docker build -t sipkes-frontend:latest ./frontend

              - name: Create temporary env file for Docker Compose
        run: |
          cat > .env <<EOF
          DB_HOST=database
          DB_USER=root
          DB_PASSWORD=oop
          DB_NAME=health_db
          JWT_SECRET=dummy_secret_for_ci
          HF_TOKEN=dummy_hf_token_for_ci
          PORT=5000
          GCS_BUCKET_NAME=sipkes-medical-documents
          GCS_KEYFILE=./gcp-service-account.json
          EOF

      - name: Validate Docker Compose File
        run: docker compose -f docker-compose.yaml config

      - name: CI/CD Status
        run: echo "Build, test, dockerize, and docker-compose validation completed successfully."